// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	Appid       pgtype.UUID
	Uid         pgtype.UUID
	Projectid   pgtype.UUID
	Coverletter *string
}

type Donation struct {
	Donationid pgtype.UUID
	Uid        pgtype.UUID
	Projectid  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

type Goal struct {
	Projectid   pgtype.UUID
	Name        string
	Goalid      pgtype.UUID
	Description *string
}

type License struct {
	Licenseid   pgtype.UUID
	Name        string
	Description string
	Permission  *string
	Condition   *string
	Limitation  string
}

type Project struct {
	Projectid   pgtype.UUID
	Title       string
	Description string
	Repoid      pgtype.UUID
	Status      *string
	CreatedAt   pgtype.Timestamptz
	Licenseid   pgtype.UUID
}

type ProjectTag struct {
	Projectid pgtype.UUID
	Tagid     pgtype.UUID
}

type Repo struct {
	Repoid      pgtype.UUID
	Uid         pgtype.UUID
	Name        string
	Url         string
	Description *string
	Star        *int32
	Fork        *int32
	LastUpdated pgtype.Timestamptz
	Language    *string
	UpdatedAt   pgtype.Timestamptz
}

type Roadmap struct {
	Projectid   pgtype.UUID
	Roadmap     string
	Description string
	Status      string
}

type Tag struct {
	Tagid pgtype.UUID
	Name  string
}

type Teammember struct {
	Projectid pgtype.UUID
	Uid       pgtype.UUID
	Role      string
}

type User struct {
	Uid               pgtype.UUID
	Login             string
	Name              string
	Avatar            *string
	Location          *string
	Token             string
	Bio               *string
	Followers         *int32
	Following         *int32
	PublicRepos       *int32
	TotalPrivateRepos *int32
	HtmlUrl           *string
	LastUpdated       pgtype.Timestamptz
}

type UserTag struct {
	Uid   pgtype.UUID
	Tagid pgtype.UUID
}
